import type { StylesheetStyle } from "cytoscape";

export const cytoscapeStyles: StylesheetStyle[] = [
  {
    selector: 'node[type="service"]',
    style: {
      shape: "roundrectangle",
      "background-color": "#0f0f1f",
      "border-color": "#3b4199",
      "border-width": 1.5,
      color: "#c7d2fe",
      label: "data(name)",
      "font-size": "10px",
      "font-weight": 500,
      "font-family": "'Geist Variable', sans-serif",
      "text-valign": "center",
      "text-halign": "center",
      width: 120,
      height: 36,
      "text-max-width": "100px",
      "text-wrap": "ellipsis",
    },
  },
  {
    selector: 'node[type="database"]',
    style: {
      shape: "roundrectangle",
      "background-color": "#0a1a14",
      "border-color": "#065f46",
      "border-width": 1.5,
      color: "#6ee7b7",
      label: "data(name)",
      "font-size": "10px",
      "font-weight": 500,
      "font-family": "'Geist Variable', sans-serif",
      "text-valign": "center",
      "text-halign": "center",
      width: 120,
      height: 36,
      "text-max-width": "100px",
      "text-wrap": "ellipsis",
    },
  },
  {
    selector: 'node[type="cache"]',
    style: {
      shape: "diamond",
      "background-color": "#1a1400",
      "border-color": "#92400e",
      "border-width": 1.5,
      color: "#fbbf24",
      label: "data(name)",
      "font-size": "10px",
      "font-weight": 500,
      "font-family": "'Geist Variable', sans-serif",
      "text-valign": "center",
      "text-halign": "center",
      width: 50,
      height: 50,
    },
  },
  {
    selector: 'node[type="external"]',
    style: {
      shape: "roundrectangle",
      "background-color": "#0d1117",
      "border-color": "#374151",
      "border-width": 1,
      color: "#9ca3af",
      label: "data(name)",
      "font-size": "9px",
      "font-weight": 500,
      "font-family": "'Geist Variable', sans-serif",
      "text-valign": "center",
      "text-halign": "center",
      width: 100,
      height: 32,
      "text-max-width": "80px",
      "text-wrap": "ellipsis",
    },
  },
  {
    selector: 'node[status="violation"]',
    style: {
      "border-color": "#dc2626",
      "border-width": 2,
      "background-color": "#1a0a0a",
      color: "#fca5a5",
    },
  },
  {
    selector: "node:selected",
    style: {
      "border-width": 2,
      "border-color": "#6366f1",
      "overlay-opacity": 0,
    },
  },
  {
    selector: 'edge[type="depends"]',
    style: {
      "line-color": "rgba(99,102,241,0.25)",
      "target-arrow-color": "rgba(99,102,241,0.35)",
      "target-arrow-shape": "triangle",
      "arrow-scale": 0.7,
      "curve-style": "bezier",
      width: 1,
      opacity: 0.8,
    },
  },
  {
    selector: "edge:selected",
    style: {
      "line-color": "rgba(99,102,241,0.6)",
      "target-arrow-color": "rgba(99,102,241,0.7)",
      width: 1.5,
    },
  },
];
