import type { StylesheetStyle } from "cytoscape";

export const cytoscapeStyles: StylesheetStyle[] = [
  {
    selector: 'node[type="service"]',
    style: {
      shape: "roundrectangle",
      "background-color": "#0f0f1f",
      "border-color": "#3b4199",
      "border-width": 1,
      color: "#c7d2fe",
      label: "data(name)",
      "font-size": "11px",
      "font-weight": 500,
      "text-valign": "center",
      "text-halign": "center",
      width: 110,
      height: 38,
    },
  },
  {
    selector: 'node[type="database"]',
    style: {
      shape: "barrel",
      "background-color": "#0a1a14",
      "border-color": "#065f46",
      "border-width": 1,
      color: "#6ee7b7",
      label: "data(name)",
      "font-size": "11px",
      "font-weight": 500,
      "text-valign": "center",
      "text-halign": "center",
      width: 110,
      height: 38,
    },
  },
  {
    selector: 'node[type="cache"]',
    style: {
      shape: "barrel",
      "background-color": "#0a1a14",
      "border-color": "#047857",
      "border-width": 1,
      color: "#6ee7b7",
      label: "data(name)",
      "font-size": "11px",
      "font-weight": 500,
      "text-valign": "center",
      "text-halign": "center",
      width: 110,
      height: 38,
    },
  },
  {
    selector: 'node[type="external"]',
    style: {
      shape: "roundrectangle",
      "background-color": "#0d1117",
      "border-color": "#374151",
      "border-width": 1,
      color: "#9ca3af",
      label: "data(name)",
      "font-size": "10px",
      "font-weight": 500,
      "text-valign": "center",
      "text-halign": "center",
      width: 90,
      height: 32,
    },
  },
  {
    selector: 'edge[type="depends"]',
    style: {
      "line-color": "rgba(99,102,241,0.3)",
      "target-arrow-color": "rgba(99,102,241,0.4)",
      "target-arrow-shape": "triangle",
      "curve-style": "bezier",
      width: 1,
    },
  },
];
