import type { GraphSnapshot } from "@invariantcontinuum/graph/react";

export const SEED_SNAPSHOT: GraphSnapshot = {
  nodes: [
    { id: "gateway",      name: "API Gateway",     type: "service",  domain: "platform", status: "healthy",   meta: {} },
    { id: "auth",         name: "Auth Service",    type: "service",  domain: "platform", status: "healthy",   meta: {} },
    { id: "order",        name: "Order Service",   type: "service",  domain: "commerce", status: "healthy",   meta: {} },
    { id: "payment",      name: "Payment Service", type: "service",  domain: "commerce", status: "violation", meta: {} },
    { id: "notification", name: "Notification",    type: "service",  domain: "platform", status: "healthy",   meta: {} },
    { id: "postgres",     name: "PostgreSQL",      type: "database", domain: "data",     status: "healthy",   meta: {} },
    { id: "redis",        name: "Redis",           type: "cache",    domain: "data",     status: "healthy",   meta: {} },
    { id: "events",       name: "Event Store",     type: "database", domain: "data",     status: "healthy",   meta: {} },
    { id: "policy-pci",   name: "PCI Boundary",    type: "policy",   domain: "security", status: "enforced",  meta: {} },
    { id: "policy-auth",  name: "Auth Required",   type: "policy",   domain: "security", status: "enforced",  meta: {} },
    { id: "adr-023",      name: "ADR-023",         type: "adr",      domain: "arch",     status: "healthy",   meta: {} },
    { id: "incident-042", name: "POST-042",        type: "incident", domain: "ops",      status: "warning",   meta: {} },
    { id: "github",       name: "GitHub",          type: "external", domain: "external", status: "healthy",   meta: {} },
    { id: "jira",         name: "Jira",            type: "external", domain: "external", status: "healthy",   meta: {} },
  ],
  edges: [
    { id: "e1",  source: "gateway",      target: "auth",         type: "depends_on", label: "",                weight: 1.0 },
    { id: "e2",  source: "gateway",      target: "order",        type: "depends_on", label: "",                weight: 1.0 },
    { id: "e3",  source: "order",        target: "payment",      type: "depends_on", label: "",                weight: 1.0 },
    { id: "e4",  source: "order",        target: "postgres",     type: "depends_on", label: "",                weight: 1.0 },
    { id: "e5",  source: "auth",         target: "redis",        type: "depends_on", label: "",                weight: 1.0 },
    { id: "e6",  source: "notification", target: "events",       type: "depends_on", label: "",                weight: 1.0 },
    { id: "e7",  source: "order",        target: "notification", type: "depends_on", label: "",                weight: 1.0 },
    { id: "ev1", source: "payment",      target: "postgres",     type: "violation",  label: "bypasses gateway", weight: 1.0 },
    { id: "ep1", source: "policy-pci",   target: "payment",      type: "enforces",   label: "",                weight: 1.0 },
    { id: "ep2", source: "policy-auth",  target: "gateway",      type: "enforces",   label: "",                weight: 1.0 },
    { id: "ew1", source: "adr-023",      target: "gateway",      type: "depends_on", label: "Gateway mandate", weight: 1.0 },
    { id: "ew2", source: "incident-042", target: "policy-auth",  type: "depends_on", label: "Caused policy",   weight: 1.0 },
    { id: "ex1", source: "github",       target: "payment",      type: "drift",      label: "drift detected",  weight: 1.0 },
    { id: "ex2", source: "jira",         target: "adr-023",      type: "depends_on", label: "",                weight: 1.0 },
  ],
  meta: { node_count: 14, edge_count: 14 },
};
