/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_renderengine_free: (a: number, b: number) => void;
export const renderengine_create: (a: any) => [number, number, number];
export const renderengine_drain_worker_messages: (a: number) => any;
export const renderengine_fit: (a: number, b: number) => void;
export const renderengine_frame: (a: number, b: number) => number;
export const renderengine_get_legend: (a: number) => any;
export const renderengine_handle_click: (a: number, b: number, c: number) => [number, number];
export const renderengine_handle_hover: (a: number, b: number, c: number) => [number, number];
export const renderengine_handle_node_drag_end: (a: number) => void;
export const renderengine_handle_node_drag_move: (a: number, b: number, c: number) => void;
export const renderengine_handle_node_drag_start: (a: number, b: number, c: number) => [number, number];
export const renderengine_handle_pan_end: (a: number) => void;
export const renderengine_handle_pan_move: (a: number, b: number, c: number) => void;
export const renderengine_handle_pan_start: (a: number, b: number, c: number) => void;
export const renderengine_handle_zoom: (a: number, b: number, c: number, d: number) => void;
export const renderengine_needs_frame: (a: number) => number;
export const renderengine_rehydrate: (a: number) => void;
export const renderengine_request_render: (a: number) => void;
export const renderengine_set_community_hulls: (a: number, b: number) => void;
export const renderengine_set_edge_metadata: (a: number, b: any, c: any) => [number, number];
export const renderengine_set_focus: (a: number, b: number, c: number) => void;
export const renderengine_set_node_ids: (a: number, b: number, c: number) => void;
export const renderengine_set_node_metadata: (a: number, b: any, c: any, d: any) => [number, number];
export const renderengine_set_theme: (a: number, b: any) => [number, number];
export const renderengine_subscribe_frame: (a: number, b: any) => void;
export const renderengine_update_edges: (a: number, b: number, c: number, d: number) => void;
export const renderengine_update_positions: (a: number, b: number, c: number, d: number, e: number) => void;
export const renderengine_zoom_in: (a: number) => void;
export const renderengine_zoom_out: (a: number) => void;
export const init: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
