parent=keycloak.v2
import=common/keycloak

meta=viewport==width=device-width,initial-scale=1
styles=css/login.css
stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css vendor/patternfly-v5/assets/icons/fontawesome.css lib/pficon/pficon.css

kcHtmlClass=invariant-login-html
kcBodyClass=invariant-login-body

kcLogin=pf-v5-c-login
kcLoginClass=pf-v5-c-login
kcLoginContainer=pf-v5-c-login__container
kcLoginMain=pf-v5-c-login__main
kcLoginMainHeader=pf-v5-c-login__main-header
kcLoginMainTitle=pf-v5-c-title pf-m-3xl
kcLoginMainHeaderUtilities=pf-v5-c-login__main-header-utilities
kcLoginMainBody=pf-v5-c-login__main-body
kcLoginFooterBand=pf-v5-c-login__main-footer-band
kcLoginFooterBandItem=pf-v5-c-login__main-footer-band-item

kcHeaderClass=pf-v5-c-login__header
kcHeaderWrapperClass=pf-v5-c-brand
kcFormHeaderClass=pf-v5-c-login__main-header
kcFormCardClass=pf-v5-c-login__main card-pf

kcFormClass=pf-v5-c-form
kcFormGroupClass=pf-v5-c-form__group
kcFormGroupLabelClass=pf-v5-c-form__group-label
kcFormGroupLabelTextClass=pf-v5-c-form__label-text
kcLabelClass=pf-v5-c-form__label
kcLabelWrapperClass=invariant-login-label-wrap
kcInputClass=pf-v5-c-form-control
kcInputGroup=pf-v5-c-input-group
kcInputGroupItemClass=pf-v5-c-input-group__item
kcInputWrapperClass=invariant-login-input-wrap
kcInputHelperTextBeforeClass=pf-v5-c-helper-text pf-v5-u-mt-xs
kcInputHelperTextAfterClass=pf-v5-c-helper-text pf-v5-u-mt-xs
kcInputErrorMessageClass=pf-v5-c-helper-text__item-text pf-m-error kc-feedback-text
kcInputRequiredClass=pf-v5-c-form__label-required
kcFormControlUtilClass=pf-v5-c-form-control__utilities
kcFormControlToggleIcon=pf-v5-c-form-control__toggle-icon
kcFormReadOnlyClass=pf-m-readonly
kcFill=pf-m-fill
kcError=pf-m-error

kcFormButtonsClass=pf-v5-c-form__actions
kcFormButtonsWrapperClass=pf-v5-c-form__actions
kcFormActionGroupClass=pf-v5-c-form__actions
kcFormOptionsClass=invariant-login-options
kcFormOptionsWrapperClass=invariant-login-options-wrap
kcFormSettingClass=invariant-login-settings
kcContentWrapperClass=pf-v5-u-mb-md
kcInfoAreaWrapperClass=pf-v5-c-login__main-footer-band-item
kcSignUpClass=invariant-login-signup
kcMarginTopClass=pf-v5-u-mt-md

kcAlertClass=pf-v5-c-alert pf-m-inline pf-v5-u-mb-md
kcAlertIconClass=pf-v5-c-alert__icon
kcAlertTitleClass=pf-v5-c-alert__title
kcAlertDescriptionClass=pf-v5-c-alert__description

kcButtonClass=pf-v5-c-button
kcButtonPrimaryClass=pf-v5-c-button pf-m-primary
kcButtonSecondaryClass=pf-v5-c-button pf-m-secondary
kcButtonDefaultClass=pf-v5-c-button pf-m-link
kcButtonBlockClass=pf-m-block
kcButtonLargeClass=invariant-login-button-lg
kcButtonLinkClass=pf-v5-c-button pf-m-link

kcCheckboxClass=pf-v5-c-check
kcCheckboxInputClass=pf-v5-c-check__input
kcCheckboxLabelClass=pf-v5-c-check__label
kcCheckboxLabelRequiredClass=pf-v5-c-check__label-required
kcCheckClass=pf-v5-c-check
kcCheckInputClass=pf-v5-c-check__input
kcCheckLabelClass=pf-v5-c-check__label
kcInputClassRadio=pf-v5-c-radio
kcInputClassRadioInput=pf-v5-c-radio__input
kcInputClassRadioLabel=pf-v5-c-radio__label
kcInputClassCheckbox=pf-v5-c-check
kcInputClassCheckboxInput=pf-v5-c-check__input
kcInputClassCheckboxLabel=pf-v5-c-check__label
kcInputClassRadioCheckboxLabelDisabled=pf-m-disabled
kcTextareaClass=pf-v5-c-form-control

kcFormPasswordVisibilityButtonClass=pf-v5-c-button pf-m-control
kcFormPasswordVisibilityIconShow=fas fa-eye
kcFormPasswordVisibilityIconHide=fas fa-eye-slash

kcFormSocialAccountSectionClass=invariant-login-social
kcFormSocialAccountListClass=pf-v5-c-login__main-footer-links
kcFormSocialAccountListGridClass=invariant-login-social-grid
kcFormSocialAccountListItemClass=pf-v5-c-login__main-footer-links-item
kcFormSocialAccountListButtonClass=pf-v5-c-login__main-footer-links-item-link
kcFormSocialAccountListButtonDisabledClass=pf-m-disabled
kcFormSocialAccountGridItem=pf-v5-c-login__main-footer-links-item
kcFormSocialAccountNameClass=invariant-login-social-name
kcCommonLogoIdP=invariant-login-social-icon

kcLocaleMainClass=invariant-login-locale
kcLocaleWrapperClass=invariant-login-locale-wrap
kcLocaleDropDownClass=invariant-login-locale-menu
kcLocaleListClass=pf-v5-c-options-menu__menu
kcLocaleListItemClass=pf-v5-c-options-menu__menu-item
kcLocaleItemClass=pf-v5-c-options-menu__menu-item-link

kcFeedbackErrorIcon=fas fa-circle-exclamation
kcFeedbackWarningIcon=fas fa-triangle-exclamation
kcFeedbackSuccessIcon=fas fa-circle-check
kcFeedbackInfoIcon=fas fa-circle-info
kcResetFlowIcon=fas fa-arrow-rotate-left

kcPanelClass=pf-v5-c-panel pf-m-raised
kcPanelMainClass=pf-v5-c-panel__main
kcPanelMainBodyClass=pf-v5-c-panel__main-body
kcListClass=pf-v5-c-list

kcSelectAuthListClass=pf-v5-c-data-list select-auth-container
kcSelectAuthListItemWrapperClass=pf-v5-c-data-list__item pf-m-clickable
kcSelectAuthListItemClass=pf-v5-c-data-list__item-row select-auth-box-parent
kcSelectAuthListItemHeadingClass=pf-v5-u-font-family-heading select-auth-box-headline
kcSelectAuthListItemBodyClass=pf-v5-c-data-list__cell pf-m-no-fill
kcSelectAuthListItemIconClass=pf-v5-c-data-list__cell pf-m-icon select-auth-box-icon
kcSelectAuthListItemIconPropertyClass=fa-2x select-auth-box-icon-properties
kcSelectAuthListItemFillClass=pf-v5-c-data-list__item-action
kcSelectAuthListItemDescriptionClass=pf-v5-c-data-list__cell pf-m-no-fill select-auth-box-desc
kcSelectAuthListItemArrowClass=pf-v5-c-data-list__item-action
kcSelectAuthListItemArrowIconClass=fas fa-angle-right
kcSelectAuthListItemTitle=select-auth-box-paragraph

kcRecoveryCodesWarning=pf-v5-c-alert pf-m-warning pf-m-inline pf-v5-u-mb-md kc-recovery-codes-warning
kcRecoveryCodesList=kc-recovery-codes-list
kcRecoveryCodesActions=kc-recovery-codes-actions
kcRecoveryCodesConfirmation=kc-recovery-codes-confirmation

kcLoginOTPListClass=pf-v5-c-tile
kcLoginOTPListInputClass=pf-v5-c-tile__input
kcLoginOTPListItemHeaderClass=pf-v5-c-tile__header pf-m-stacked
kcLoginOTPListItemIconBodyClass=pf-v5-c-tile__icon
kcLoginOTPListItemIconClass=fas fa-mobile-screen-button
kcLoginOTPListItemTitleClass=pf-v5-c-tile__title
kcLoginOTPListSelectedClass=pf-m-selected

kcWebAuthnKeyIcon=pf-v5-c-icon pf-m-lg fas fa-key
kcWebAuthnDefaultIcon=pf-v5-c-icon pf-m-lg fas fa-shield-halved
kcWebAuthnUnknownIcon=pf-v5-c-icon pf-m-lg fas fa-key
kcWebAuthnUSB=fas fa-usb
kcWebAuthnNFC=fas fa-wifi
kcWebAuthnBLE=fab fa-bluetooth-b
kcWebAuthnInternal=fas fa-key

kcLogoIdP-google=fab fa-google
kcLogoIdP-github=fab fa-github
kcLogoIdP-linkedin=fab fa-linkedin
kcLogoIdP-linkedin-openid-connect=fab fa-linkedin
kcLogoIdP-microsoft=fab fa-microsoft
kcLogoIdP-gitlab=fab fa-gitlab
kcLogoIdP-bitbucket=fab fa-bitbucket
kcLogoIdP-facebook=fab fa-facebook
kcLogoIdP-instagram=fab fa-instagram
kcLogoIdP-paypal=fab fa-paypal
kcLogoIdP-stackoverflow=fab fa-stack-overflow
kcLogoIdP-twitter=fab fa-x-twitter
kcLogoIdP-openshift-v4=pf-icon pf-icon-openshift
kcLogoIdP-openshift-v3=pf-icon pf-icon-openshift
