#!/usr/bin/env bash
# Configure substrate for a deployment mode (dev|prod).
#
# Materializes env/platform.env, env/infra.env, env/llm.env from their
# .example siblings (non-destructive), regenerates env/overlays/<mode>.env
# from env/overlays/<mode>.env.example with domain/scheme substitutions,
# concatenates everything into the top-level .env docker-compose reads,
# records the active mode in .deploy-mode, and renders the Keycloak realm
# JSON from the template.
#
# Usage:
#   scripts/set-env.sh dev
#   scripts/set-env.sh prod --domain=example.com [--acme-email=you@example.com]
set -euo pipefail

usage() {
    cat >&2 <<'EOF'
Usage: scripts/set-env.sh <dev|prod> [--domain=<root-domain>] [--acme-email=<email>]

dev:  all services bind to localhost.
prod: --domain=<root-domain> is required; Keycloak lives at auth.<domain>,
      frontend at app.<domain>. --acme-email defaults to admin@<domain>.
EOF
    exit 2
}

[[ $# -ge 1 ]] || usage
MODE="$1"; shift || true
DOMAIN=""
ACME_EMAIL=""
for arg in "$@"; do
    case "$arg" in
        --domain=*)     DOMAIN="${arg#*=}" ;;
        --acme-email=*) ACME_EMAIL="${arg#*=}" ;;
        *) echo "unknown arg: $arg" >&2; usage ;;
    esac
done

case "$MODE" in
    dev)
        if [[ -n "$DOMAIN" ]]; then
            echo "error: --domain is not valid for dev mode" >&2
            exit 2
        fi
        ;;
    prod)
        if [[ -z "$DOMAIN" ]]; then
            echo "error: prod requires --domain=<root-domain>" >&2
            exit 2
        fi
        if [[ "$DOMAIN" == "localhost" || "$DOMAIN" == *"example.com" ]]; then
            echo "error: pick a real domain; '$DOMAIN' is not deployable" >&2
            exit 2
        fi
        [[ -n "$ACME_EMAIL" ]] || ACME_EMAIL="admin@${DOMAIN}"
        ;;
    *) usage ;;
esac

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# 1. Materialize / migrate base env files against their examples.
#    Rule: for every key in <base>.env.example, keep the existing value if
#    the file already defines it, otherwise use the example's value. Keys
#    no longer in the example are dropped (they moved to overlays or were
#    removed). Comments come from the example.
sync_env_to_example() {
    local target="$1" source="$2"
    if [[ ! -f "$target" ]]; then
        cp "$source" "$target"
        echo "  created $target from example (edit secrets as needed)"
        return
    fi
    python3 - "$target" "$source" <<'PY'
import sys, re
target, source = sys.argv[1], sys.argv[2]
kv_re = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
existing = {}
with open(target) as f:
    for line in f:
        m = kv_re.match(line.strip())
        if m:
            existing[m.group(1)] = m.group(2)
out_lines = []
with open(source) as f:
    for raw in f:
        stripped = raw.rstrip("\n")
        m = kv_re.match(stripped.strip())
        if m and m.group(1) in existing:
            out_lines.append(f"{m.group(1)}={existing[m.group(1)]}")
        else:
            out_lines.append(stripped)
with open(target, "w") as f:
    f.write("\n".join(out_lines) + "\n")
PY
    echo "  synced $target against $source"
}

for base in platform infra llm; do
    sync_env_to_example "env/${base}.env" "env/${base}.env.example"
done

# 2. Generate the overlay file for this mode.
OVERLAY_OUT="env/overlays/${MODE}.env"
if [[ "$MODE" == "dev" ]]; then
    cat > "$OVERLAY_OUT" <<'EOF'
# Generated by scripts/set-env.sh dev. Do not edit by hand.
DEPLOYMENT_MODE=dev
ROOT_DOMAIN=localhost
SCHEME=http
FRONTEND_HOST_PORT=3535
KEYCLOAK_HOST_PORT=8080
GATEWAY_HOST_PORT=8180
INGESTION_HOST_PORT=8181
GRAPH_HOST_PORT=8182
POSTGRES_HOST_PORT=5432
PGADMIN_HOST_PORT=5050
APP_URL=http://localhost:3535
AUTH_URL=http://localhost:8080
KEYCLOAK_ISSUER=http://localhost:8080/realms/substrate
KC_HOSTNAME=http://localhost:8080
KC_HOSTNAME_STRICT=false
KC_HTTP_ENABLED=true
KC_START_COMMAND=start-dev
VITE_KEYCLOAK_URL=http://localhost:8080
CORS_ORIGINS=["http://localhost:3535","http://localhost:3000"]
AUTH_DISABLED=false
EOF
else
    cat > "$OVERLAY_OUT" <<EOF
# Generated by scripts/set-env.sh prod --domain=${DOMAIN}. Do not edit by hand.
DEPLOYMENT_MODE=prod
ROOT_DOMAIN=${DOMAIN}
SCHEME=https
APP_SUBDOMAIN=app
AUTH_SUBDOMAIN=auth
ACME_EMAIL=${ACME_EMAIL}
APP_URL=https://app.${DOMAIN}
AUTH_URL=https://auth.${DOMAIN}
KEYCLOAK_ISSUER=https://auth.${DOMAIN}/realms/substrate
KC_HOSTNAME=https://auth.${DOMAIN}
KC_HOSTNAME_STRICT=true
KC_HTTP_ENABLED=false
KC_START_COMMAND=start
VITE_KEYCLOAK_URL=https://auth.${DOMAIN}
CORS_ORIGINS=["https://app.${DOMAIN}"]
AUTH_DISABLED=false
EOF
fi
echo "  wrote $OVERLAY_OUT"

# 3. Concatenate every sourced env file into top-level .env.
{
    echo "# Generated by scripts/set-env.sh ${MODE}. Do not edit by hand."
    echo "# Regenerate via: make configure MODE=${MODE}${DOMAIN:+ DOMAIN=${DOMAIN}}"
    echo
    for f in env/platform.env env/infra.env env/llm.env "$OVERLAY_OUT"; do
        echo "# --- ${f} ---"
        grep -Ev '^\s*(#|$)' "$f" || true
        echo
    done
} > .env
echo "  wrote .env"

# 4. Render the Keycloak realm JSON using the materialized env.
set -a
# shellcheck disable=SC1090,SC1091
. .env
set +a

python3 scripts/render-realm.py

# 5. Persist the active mode for Make to consume.
echo "$MODE" > .deploy-mode
echo "  wrote .deploy-mode (${MODE})"

echo
echo "configured substrate for ${MODE}${DOMAIN:+ on ${DOMAIN}}"
