#version 300 es
precision highp float;
layout(location = 0) in vec2 a_position;
layout(location = 1) in vec2 a_center;
layout(location = 2) in float a_half_w;
layout(location = 3) in float a_half_h;
layout(location = 4) in vec4 a_color;
layout(location = 5) in vec4 a_border_color;
layout(location = 6) in float a_border_width;
layout(location = 7) in float a_shape;
layout(location = 8) in float a_flags;
uniform mat4 u_vp;
uniform float u_time;
out vec2 v_local;
out vec4 v_color;
out vec4 v_border_color;
out float v_border_width;
out float v_shape;
out float v_radius;
out float v_flags;
void main() {
    float flags = a_flags;
    bool pulse = mod(flags, 2.0) > 0.5;
    bool hovered = mod(floor(flags / 2.0), 2.0) > 0.5;
    bool selected = mod(floor(flags / 4.0), 2.0) > 0.5;
    float scale_mod = 1.0;
    if (pulse)   scale_mod *= 1.0 + 0.08 * sin(u_time * 3.0);
    if (hovered) scale_mod *= 1.3;
    if (selected) scale_mod *= 1.0 + 0.04 * sin(u_time * 6.0);
    vec2 half_size = vec2(a_half_w, a_half_h) * scale_mod;
    vec2 world = a_center + a_position * half_size;
    gl_Position = u_vp * vec4(world, 0.0, 1.0);
    v_local        = a_position;
    v_color        = a_color;
    v_border_color = a_border_color;
    float effective = max(half_size.x, half_size.y);
    v_border_width = a_border_width / effective;
    if (pulse) v_border_width *= 1.0 + 0.4 * (0.5 + 0.5 * sin(u_time * 3.0));
    v_shape        = a_shape;
    v_radius       = effective;
    v_flags        = flags;
}
